config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'authors#index', as: 'home'

  resources :authors
  resources :books
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
  has_many :books
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :year_of_birth, presence: true
  validates :biography, presence: true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  belongs_to :position
  belongs_to :author
  has_and_belongs_to_many :genres

  validates_uniqueness_of :position
  validates :title, presence: true
  validates :year_of_release, presence: true
  validates :description, presence: true
end

app/models/books_genre.rb
# frozen_string_literal: true

class BooksGenre < ApplicationRecord
  belongs_to :book_id
  belongs_to :genre_id
end

app/models/genre.rb
# frozen_string_literal: true

class Genre < ApplicationRecord
  has_and_belongs_to_many :books
end

app/models/position.rb
# frozen_string_literal: true

# Position
class Position < ApplicationRecord
  MAX_POSITION = 4
  has_one :book

  validates :row, uniqueness: { scope: :position }, presence: true
  validates :position, presence: true, numericality: { less_than_or_equal_to: MAX_POSITION }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
# frozen_string_literal: true

# authors controller
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  # if you wanna check all actions from resources: 'rake routes'
  def new
    @author = Author.new
  end

  def show
    @author = Author.find(params[:id])
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to author_path(@author) # calls 'show'
    else
      render :edit # rerender the current page
    end
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to author_path(@author) # calls 'show'
    else
      render :new # rerender the current page
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to home_path
  end

  private

  def author_params
    params.require(:author).permit(:first_name, :last_name, :patronymic, :year_of_birth, :biography)
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

# books controller
class BooksController < ApplicationController
  def index
    @books = Book.includes(:author, :genres, :position).all
    @positions = Position.includes(:book).all
  end

  # if you wanna check all actions from resources: 'rake routes'
  def new
    @book = Book.new
    @genres = Genre.all
  end

  def show
    @book = Book.find(params[:id])
    @genres = Genre.all
  end

  def edit
    @book = Book.find(params[:id])
    @genres = Genre.all
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to book_path(@book) # calls 'show'
    else
      render :edit # rerender the current page
    end
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book) # calls 'show'
    else
      render :new # rerender the current page
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to home_path
  end

  private

  def book_params
    params[:book][:genre_ids] = (params[:book][:genre_ids] || {}).values.map(&:to_i)
    params.require(:book).permit(:title, :year_of_release, :description, :author_id, :position_id, genre_ids: [])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# application helper
module ApplicationHelper
end

app/helpers/authors_helper.rb
# frozen_string_literal: true

# authors helper
module AuthorsHelper
  def author_fullanme(author)
    [author.first_name, author.last_name, author.patronymic].select(&:present?).join(' ')
  end
end

app/helpers/books_helper.rb
# frozen_string_literal: true

# books helper
module BooksHelper
  def authors_for_select
    Author.all.collect { |author| [author_fullanme(author), author.id] }
  end

  def positions_for_select
    Position.joins('LEFT JOIN books ON positions.id = books.position_id')
            .where('books.id IS NULL')
            .order(:id).collect { |position| [generate_shelf(position.row, position.position), position.id] }
  end

  def generate_shelf(row, position)
    "Shelf #{row}, Position #{position}"
  end

  def author_fullanme(author)
    [author.first_name, author.last_name, author.patronymic].select(&:present?).join(' ')
  end
end

app/views/authors/_form.html.erb
<div class="card" style="width: 50rem; padding: 20px; margin: 0 auto">
  <%= form_for @author do |form| %> 
    <div class="mb-3">
      <%= form.label :first_name, class: "form-label" %>
      <%= form.text_field :first_name, required: true, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :last_name, class: "form-label" %>
      <%= form.text_field :last_name, required: true, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :patronymic, class: "form-label" %>
      <%= form.text_field :patronymic, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :year_of_birth, class: "form-label" %>
      <%= form.text_field :year_of_birth, required: true, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :biography, class: "form-label" %>
      <%= form.text_area :biography, required: true, class: "form-control" %>
    </div>

    <div>
      <%= form.submit("Send", {:class => 'btn btn-primary'}) %>
    </div>
  <% end %>
</div>

app/views/authors/edit.html.erb
<div class="container align-items-center"> 
  <div class="d-flex">
    <h1 class="mb-3 mt-5" style="margin: 0 auto; padding: 20px">
      Edit author
    </h1> 
  </div>
  <div class="d-flex justify-content-between align-items-center" style="margin: 0 auto; padding: 20px"> 
    <%= render 'form', author: @author %>
  </div>
</div>

app/views/authors/index.html.erb
<div class="container"> 
  <% if @authors.empty? %>
    <div class="d-flex">
      <h1 class="mb-3 mt-5" style="margin: 0 auto; padding: 20px">
        Add the first author 
        <%= link_to new_author_path(@author), class: "btn btn-outline-primary btn-md" do %>
          <i class="bi-plus-lg" ></i>  
        <% end %>
      </h1> 
    </div> 
  <% else %>
    <div class="d-flex">
      <h1 class="mb-3 mt-5" style="margin: 0 auto; padding: 20px">
        All authors  
        <%= link_to new_author_path(@author), class: "btn btn-outline-primary btn-md" do %>
          <i class="bi-plus-lg" ></i>  
        <% end %>
      </h1> 
    </div> 
    <div class="d-flex justify-content-between align-items-center" style="margin: 0 auto; padding: 20px"> 
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Year of birth</th>
            <th scope="col">Edit author</th>
            <th scope="col">Delete author</th>
          </tr>
        </thead>
        <tbody>
          <% @authors.each do |author| %>
            <tr>
              <td> <%= link_to author_fullanme(author), author_path(author), { :class => 'text-decoration-none text-primary' } %>  </td>
              <td> <%= author.year_of_birth %> </td>
              <td> 
                <%= link_to edit_author_path(author), class: "btn btn-md" do %>
                  <i class="bi-pen" ></i>  
                <% end %>
              </td>
              <td> 
                <%= link_to author_path(author), method: :delete, data: {confirm: "Delete author?"}, class: "btn btn-md" do %>
                  <i class="bi-trash" ></i>  
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody
      </table>
    </div>
  <% end %>
</div>

app/views/authors/new.html.erb
<div class="container align-items-center"> 
  <div class="d-flex">
    <h1 class="mb-3 mt-5" style="margin: 0 auto; padding: 20px">
      Add author
    </h1> 
  </div>
  <div class="d-flex justify-content-between align-items-center" style="margin: 0 auto; padding: 20px"> 
    <%= render 'form', author: @author %>
  </div>
</div>

app/views/authors/show.html.erb
<div class="card border-primary mb-3 mt-5 w-25" style="margin:0 auto">
  <div class="card-header"> 
    <%= author_fullanme(@author) %> 
  </div>
  <div class="card-body">
    <p class="card-text"> Born in <b> <%= @author.year_of_birth %> </b> </p>
    <p class="card-text"> <%= @author.biography %> </p>
  </div>
</div> 

<div class="d-flex">
  <h3 class="mb-3 mt-5" style="margin: 0 auto; padding: 20px">
    Author's books
  </h3> 
</div>
<div class="container w-50"> 
  <div class="d-flex justify-content-between align-items-center" style="margin: 0 auto; padding: 20px"> 
      <table class="table">
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Year of release</th>
        </tr>
      </thead>
      <tbody>
        <% @author.books.each do |book| %>
          <tr>
            <td> <%= link_to book.title, book_path(book), { :class => 'text-decoration-none text-primary' }%>  </td>
            <td> <%= book.year_of_release %> </td>
          </tr>
        <% end %>
      </tbody
    </table>
  </div>
</div>

app/views/books/_form.html.erb
<div class="card" style="width: 50rem; padding: 20px; margin: 0 auto">
  <%= form_for @book do |form| %>
      <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, required: true, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :year_of_release, class: "form-label" %>
        <%= form.text_field :year_of_release, required: true, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :description, class: "form-label" %>
        <%= form.text_area :description, required: true, class: "form-control" %>
      </div>
      
      <div class="mb-3">
        Author: 
        <%= form.select :author_id, authors_for_select, class:'form-select form-select-lg mb-3' %>      
      </div>

      <div class="mb-3">
        Genre: 
        <% @genres.each_with_index do |genre, i| %>
          <%= check_box_tag "book[genre_ids][#{i}]", genre.id, class: "form-check" %>
          <%= label_tag "book[genre_ids][#{i}]", genre.name, class: "form-check-label" %>
        <% end %>
      </div>
      
      <div class="mb-3">
        Position: 
        <%= form.select :position_id, positions_for_select, class:'form-select form-select-lg mb-3' %>      
      </div>

      <div>
        <%= form.submit("Send", {:class => 'btn btn-primary'}) %>
      </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container align-items-center"> 
  <div class="d-flex">
    <h1 class="mb-3 mt-5" style="margin: 0 auto; padding: 20px">
      Edit book
    </h1> 
  </div>
  <div class="d-flex justify-content-between align-items-center" style="margin: 0 auto; padding: 20px"> 
    <%= render 'form', book: @book %>
  </div>
</div>

app/views/books/index.html.erb
<div class="container"> 
  <div class="d-flex">
    <h1 class="mb-3 mt-5" style="margin: 0 auto; padding: 20px">
      All books  
      <%= link_to new_book_path(@book), class: "btn btn-outline-primary btn-md" do %>
        <i class="bi-plus-lg" ></i>  
      <% end %>
    </h1> 
  </div>
  <div class="d-flex justify-content-between align-items-center" style="margin: 0 auto; padding: 20px"> 
    <% @positions.each do |pos| %>
      <% if pos.book == nil %>
      <div class="card border-secondary mb-3" style="width: 17rem; height: 12rem">
        <div class="card-header"></div>
        <div class="card-body text-secondary">
          <h5 class="card-title">Empty shelf</h5>
        </div>
      </div>
      <% else %>
        <div class="card border-primary mb-3" style="width: 17rem; height: 12rem">
          <div class="card-header"> 
            <%= link_to author_fullanme(pos.book.author), author_path(pos.book.author), { :class => 'text-decoration-none text-primary' }%> 
            <%= link_to edit_book_path(pos.book), class: "btn btn-sm" do %>
              <i class="bi-pen" ></i>  
            <% end %>
            <%= link_to book_path(pos.book), method: :delete, data: {confirm: "Delete book?"}, class: "btn btn-sm" do %>
              <i class="bi-trash" ></i>  
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"> <%= link_to pos.book.title, book_path(pos.book), { :class => 'text-decoration-none text-dark' }%> </h5>
          </div>
          <div class="card-body">
            <% pos.book.genres.each do |genre| %> 
              <b class="border border-primary rounded p-1 m-1"> <%= genre.name %> </b>
            <% end %> 
          </div>   
        </div>
      <% end %>
      <% if pos.position == Position::MAX_POSITION %>
        </div>
        <div class="d-flex justify-content-between align-items-center" style="margin: 0 auto; padding: 20px"> 
      <% end %>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<div class="container align-items-center"> 
  <div class="d-flex">
    <h1 class="mb-3 mt-5" style="margin: 0 auto; padding: 20px">
      Add book
    </h1> 
  </div>
  <div class="d-flex justify-content-between align-items-center" style="margin: 0 auto; padding: 20px"> 
    <%= render 'form', book: @book %>
  </div>
</div>

app/views/books/show.html.erb
<div class="card border-primary mb-3 mt-5 w-25" style="margin:0 auto">
  <div class="card-header"> 
    <%= link_to author_fullanme(@book.author), author_path(@book.author), { :class => 'text-decoration-none text-primary' }%> 
  </div>
  <div class="card-body">
    <h5 class="card-title"> <%= @book.title %> </h5>
    <p class="card-text"> Published in <b> <%= @book.year_of_release %> </b> </p>
    <p class="card-text"> <%= @book.description %> </p>
  </div>
</div> 

app/views/layouts/_header.html.erb
<div class="d-flex justify-content-between w-50 align-items-center border-bottom" style="margin: 0 auto; padding: 20px"> 
    <%=link_to 'All books', books_path, class: 'btn btn-primary' %>
    <%=link_to 'All authors', home_path, class: 'btn btn-primary' %>
    <%=link_to 'Admin button', rails_admin_path, class: 'btn btn-secondary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/header' %>
  <body>
    <%= yield %>
  </body>
</html>